### ISSUE TITLE
Convert numberbatch text file to magnitude format

### ISSUE THREAD

**Issue by Shubham067** [plasticityai/magnitude#12]
I am trying to convert a "numberbatch-en.txt" pre-trained word vector file to magnitude format using the converter but it's throwing ValueError. Is it only useful for converting glove & word2vec pre-trained files?
[https://github.com/commonsense/conceptnet-numberbatch](url)
![screenshot 29](https://user-images.githubusercontent.com/17729536/41021043-a496065c-6982-11e8-9808-754821f88ff5.png)
@AjayP13 @acsands13 Please look into this issue.Thanks!

**Comment by Shubham067** [comment]
Thanks @plasticity-admin. The issue got resolved now!

**Comment by AjayP13** [comment]
Your welcome! I also performed the conversion on Numberbatch and hosted the files here:

[Light](http://magnitude.plasticity.ai/numberbatch/numberbatch-en-17.06.magnitude), [Medium](http://magnitude.plasticity.ai/numberbatch+subword/numberbatch-en-17.06.magnitude), [Heavy](http://magnitude.plasticity.ai/numberbatch+approx/numberbatch-en-17.06.magnitude)

in case you run into any other problems, but it should be resolved now. 

The issue was we unit-length normalize vectors and Numberbatch has one zero vector in it which is a mathematically degenerate case that cannot be unit-length normalized as it involves a division by zero:
![image](https://user-images.githubusercontent.com/5404177/41048465-9a2009b2-6963-11e8-9ca5-bfe786f3950a.png)
