### ISSUE TITLE
Not possible to download the datasets

### ISSUE THREAD

**Issue by dinel** [plasticityai/magnitude#13]
I attempted a few times to download the datasets, but each time the download stopped after less than 100k of data was received. I don't know whether this is a temporary server issue. Do you have plans to host the files somewhere else? 

The conversion from Glove to your format worked flawlessly, but maybe not everyone has the time and resources to perform it.

**Comment by AjayP13** [comment]
Hi @dinel,

Thanks for reporting the issue. That's strange, it seems like its working for me. They are hosted directly on AWS S3 with no CDN or server in-front of it so I cannot imagine what would be the issue other than an Amazon S3 outage. Are you in a country / network that is blocking AWS S3 connections by any chance?

Does downloading straight from the S3 bucket URL work for you?
[https://s3.amazonaws.com/magnitude.plasticity.ai/glove/glove.6B.50d.magnitude](https://s3.amazonaws.com/magnitude.plasticity.ai/glove/glove.6B.50d.magnitude)

– Ajay

**Comment by dinel** [comment]
I am downloading from my university in UK where speed and AWS are definitely not a problem. The link you send me worked without a problem (but it may be because it's a small file). 

I tried again http://magnitude.plasticity.ai/glove+subword/glove.840B.300d.magnitude
and it stopped again at 0.1/3.4 GB. 

I tried also with wget and after 4% of the file is downloaded at decent speed, the speed drops to 0 Kb/s, which suggests to me that the server is throttling the download. 

I hope this help,

Constantin

**Comment by AjayP13** [comment]
Just released version 0.1.46. You can now disable downloading the wheel and force it to compile instead by running this command in your shell instead:

```bash
SKIP_MAGNITUDE_WHEEL=1 pip3 install pymagnitude==0.1.46 -vvvv
```

I think the downloading and installing of the wheel is just taking extra long on your computer / network, but if you really need to skip it, try running this command. 

Note: It is actually slower than installing a wheel since it will have to run GCC to compile some large C code instead of using a pre-built binary. But it seems like the bottleneck on your computer is downloading the wheel.

**Comment by dinel** [comment]
This morning when I received this message I could not download from either of the links. Amazon S3 was giving me an error, however that error is now gone and I can download the file from there. Going via your domain is still a problem. Given that I am the first one to complain about this, it is probably an issue that affects only me. Probably you can close the ticket.

Regards,

Constantin

**Comment by AjayP13** [comment]
Got it, it does seem to be the domain then. You can prepend that AWS domain in front of any "magnitude.plasticity.ai" domains and it should give you a download that works for you. I suspect proxying your connection might work as well since it might be a firewall / ISP issue.

Thanks for trying it out.
