### ISSUE TITLE
Non-unit length word vectors

### ISSUE THREAD

**Issue by jsedoc** [plasticityai/magnitude#18]
Hi, occasionally I want to use raw vectors and not demean and normalize. Is there a way to do this?

**Comment by AjayP13** [comment]
Hi, 

No way to do this, unfortunately. I didn't anticipate people would have any use for the non-normalized forms since they are usually not used in ML models and they take extra computation at runtime to compute the normalized version or space to store both versions. You could separately store the magnitudes of each vector and denormalize, but I probably won't add this to the package for that reason.

**Comment by AjayP13** [comment]
This is now coming as a feature. It seems as though some people have a use case for this. Will ping this issue if it's still of interest when it is released.

**Comment by jsedoc** [comment]
Awesome! That's great and definitely of use to me for some of my research.

**Comment by AjayP13** [comment]
As mentioned at EMNLP, this is now a part of the library!

The constructor now takes a `normalized` parameter that you can use to turn normalization on and off. It is documented [here](https://github.com/plasticityai/magnitude#constructing-a-magnitude-object). Note: You will have to re-download the `.magnitude` file for the model you are using or re-convert it if it is your own for this to work. You can download them again from [here](https://github.com/plasticityai/magnitude/#pre-converted-magnitude-formats-of-popular-embeddings-models).

**Comment by jsedoc** [comment]
Awesome! Thanks very much.
