### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by alexpnt** [plasticityai/magnitude#22]
First of all: Nice work in implementing useful tasks such as lazy loading and memory mapped files .   

As a suggestion, I think it would be nice to have an option regarding the normalization. I might need the vectors as they are and not normalized.

**Comment by AjayP13** [comment]
Thanks!

This is coming! Unfortunately, it will take some time as I will have to re-convert all the pre-converted models before releasing this release. I will ping you on this issue when it comes out.

**Comment by AjayP13** [comment]
Sorry, this took longer than normal. It required a re-work of the library and file format since when I created this I didn't actually encode the non-normalized vector information in the files.

The constructor now takes a `normalized` parameter that you can use to turn normalization on and off. It is documented [here](https://github.com/plasticityai/magnitude#constructing-a-magnitude-object). Note: You will have to re-download the `.magnitude` file for the model you are using or re-convert it if it is your own for this to work. You can download them again from [here](https://github.com/plasticityai/magnitude/#pre-converted-magnitude-formats-of-popular-embeddings-models).
