### ISSUE TITLE
Is there a way to read the magnitude files from s3 ?

### ISSUE THREAD

**Issue by mohammad1234** [plasticityai/magnitude#36]
Is there a way to read the magnitude files from s3

**Comment by AjayP13** [comment]
Yes, it is documented here: https://github.com/plasticityai/magnitude#remote-streaming-over-http

You can see an example Python notebook here: https://colab.research.google.com/drive/1zkPhoNM1NvbTmEk9gr0Jnt8hONrca1Fv

Keep in mind this is still an alpha feature, if you really need performance and speed download the ".magnitude" file instead of streaming it over an internet connection.

**Comment by mohammad1234** [comment]
Thanks ... i will try it out
