### ISSUE TITLE
Long time to install

### ISSUE THREAD

**Issue by gladuo** [plasticityai/magnitude#40]
I have seen your efforts on installing this package and its dependencies, and I appreciate your great job.
But it still takes more than an hour installing this package in China, either SKIP_ or not.
So I hope if you could build most of things as binary wheels and let them be downloaded in github for faster installing.
Again, thank you for your time.

**Comment by AjayP13** [comment]
Hm, that's interesting.

There are two options to install Magnitude as you mentioned:

1. Install normally. This does actually install with binary wheels (if your system is supported Mac, Linux, some Windows). It doesn't download the wheel from PyPI, however, as I made the install script download it from our S3 bucket for reasons. However, it should be coming from `us-east-1` Amazon S3 which is quite far from China, but still shouldn't be that big of a problem IMO (let me know if that is an issue, maybe I can set up a CDN). I actually bundle all of the recursive dependencies (`numpy`, `torch`) as binary wheels as well, to prevent C compilation issues during install. So the binary wheel actually gets quite large (~120-300MB). The download is a little slow for 120-300MB, but the installation is pretty much instant since there is nothing to build. Here in the USA 120MB downloads pretty quickly even at most residential internet speeds.

2. Build from source (`SKIP_MAGNITUDE_WHEEL`). You can build from source by passing this flag. If a wheel for your system is not supported, it will build from source. This can be slow. It has to compile 2 versions of SQLite, and if your system doesn't have `numpy` or `torch` it may compile those as well.

Could you answer some questions to help debug:
1. Do you have this problem with other packages as well? I'm not very familiar with the internet situation in China, but is there throttling of US websites / is the overall internet speed low? 
2. Would downloading 120-300MB from Amazon S3 take a long time?
3. Why do you need to install Magnitude over and over again? Are you installing it on a production server? Are you installing inside a Docker image?

**Comment by gladuo** [comment]
@AjayP13 
1. `pip install` using official pypi source downloads slowly in China, but we have lots of mirrors of pypi, by using the mirror source, `pip install` goes fast as 50MB/s+. Generally, US website goes slower in China as half planet long way to transfer.
2. AWS US might go slow in China. Would you mind give me a link of some big files so I could clearly give you the speed? I think adding CDN or an offline wheel zip should be much better.
3. Yeah, I plan to use it in a Docker image.

**Comment by AjayP13** [comment]
1. Got it, that makes sense. Since we are using our S3 server for the wheel download, it might not be taking advantage of the PyPI China mirrors.

2. Try downloading this: https://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.119-cp36-cp36m-manylinux1_x86_64.whl (Python 3.6 Linux x86_64 Binary Wheel Magnitude Version: 0.1.119) and tell me if that is slow and how long it takes. (It's 135MB)

If #2 is where the slowness is coming from I will set up an Amazon CloudFront CDN to mirror the files globally. 

If #2 is fast enough, downloading is probably not the bottleneck, it is probably building from source on your computer, which is why it is slow (SQLite is slow to compile). Please run `pip install magnitude -vvv` (verbose mode logging) and paste the log here in that case.

**Comment by AjayP13** [comment]
I can't use PyPI for the wheel. It's not a standard wheel, its a modified wheel file that I made. The `setup.py` file that is run when you install using `pip` will install it correctly.

The real issue is why you are getting `Unable to establish SSL connection.`. Can you paste the full log? I don't think this is caused by internet issues or server issues. I think your system has an SSL issues due to maybe outdated SSL libraries.

**Comment by gladuo** [comment]
@AjayP13 😅I use wget in Aliyun to download the link above, when I use `http`, it downloads fast every time, and when I use `https`, it just hungs like
```
wget https://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.119-cp36-cp36m-manylinux1_x86_64.whl
--2018-11-28 10:39:15--  https://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.119-cp36-cp36m-manylinux1_x86_64.whl
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.161.245
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.161.245|:443...
```

**Comment by gladuo** [comment]
@AjayP13 Good and Bad.
1. Using `http` helps a lot in connection success rate, thank you.
2. When I wget `http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.120-cp36-cp36m-manylinux1_x86_64.whl` in 7 hours ago and now, I both got a speed of less than 100KB/s, compared with 0.1.119 of 1MB/s and more. I will send more feedback and cdn might be needed.

**Comment by gladuo** [comment]
@AjayP13 Test more. 
1. Sometimes both in Aliyun and AWS China, I only got less than 50KB/s download speed. Sometimes 2MB/s+. No pattern founded. Just really not stable. Poor network between China and US.
2. Using CDN is great, and add an parameter for load an offline `pymagnitude-0.1.120-cp36-cp36m-manylinux1_x86_64.whl` is also good enough.
Thank you for your time.

**Comment by TuGengs** [comment]
> 1. Got it, that makes sense. Since we are using our S3 server for the wheel download, it might not be taking advantage of the PyPI China mirrors.
> 2. Try downloading this: https://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.119-cp36-cp36m-manylinux1_x86_64.whl (Python 3.6 Linux x86_64 Binary Wheel Magnitude Version: 0.1.119) and tell me if that is slow and how long it takes. (It's 135MB)
> 
> If 2) is where the slowness is coming from I will set up an Amazon CloudFront CDN to mirror the files globally.
> 
> If 2) is fast enough, downloading is probably not the bottleneck, it is probably building from source on your computer, which is why it is slow (SQLite is slow to compile). Please run `pip install pymagnitude -vvv` (verbose mode logging) and paste the log here in that case.


Can you provide windows version?
