### ISSUE TITLE
Error while trying to pip install pymagnitude

### ISSUE THREAD

**Issue by shaurya27** [plasticityai/magnitude#48]
```Collecting pymagnitude
  Using cached https://files.pythonhosted.org/packages/0a/a3/b9a34d22ed8c0ed59b00ff55092129641cdfa09d82f9abdc5088051a5b0c/pymagnitude-0.1.120.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-guvdu2_b/pymagnitude/setup.py", line 178, in <module>
        'a+')
    PermissionError: [Errno 13] Permission denied: '/tmp/magnitude.install'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-guvdu2_b/pymagnitude/```

**Comment by AjayP13** [comment]
Try to use sudo when installing.

**Comment by mittalsuraj18** [comment]
is it possible to resolve this issue without sudo.
asking because i am trying to install it in a workspace computer without sudo access

**Comment by AjayP13** [comment]
Seems like if you set ‘TMPDIR‘ in your shell to a directory you can access without sudo it would work. Note, that even if you get Magnitude to install it uses the temporary directory a lot at run time, so you will need to set this variable every time it the shell in which you run Magnitude. I would recommend adding it to your bashrc file.

**Comment by sidhantls** [comment]
Had the same permissions during installation, but created a workaround for this. The error is on L178 of `setup.py`.  Use cwd instead of the temp dir, which requires permission to access, and install from source

Try installing from this fork. `git clone --single-branch --branch mag_install https://github.com/sid-sundrani/magnitude` and run `pip install .`
